ALTER TABLE public.sales
  ALTER COLUMN buyer DROP NOT NULL,
  ALTER COLUMN quantity DROP NOT NULL,
  ALTER COLUMN unit DROP NOT NULL,
  ALTER COLUMN unit_price DROP NOT NULL,
  ALTER COLUMN product_name DROP NOT NULL,
  ALTER COLUMN product_id DROP NOT NULL,
  ALTER COLUMN product_type DROP NOT NULL;

ALTER TABLE public.purchases
  ALTER COLUMN supplier DROP NOT NULL,
  ALTER COLUMN quantity DROP NOT NULL,
  ALTER COLUMN unit DROP NOT NULL,
  ALTER COLUMN unit_cost DROP NOT NULL,
  ALTER COLUMN item_name DROP NOT NULL,
  ALTER COLUMN category DROP NOT NULL;